'use client'

import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, Package, CreditCard, X, CheckCircle2, Clock, RefreshCw, WifiOff } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { useAppStore } from '@/lib/stores/app-store'
import { formatFCFA } from '@/lib/utils'
import { tataSpeak, haptic, playBeep } from '@/lib/voice/tata-tts'
import { useNetworkStatus } from '@/lib/hooks/use-network-status'

type Order={id:string;order_number:string;total_cfa:number;status:string;payment_status:string;payment_method:string|null;delivery_status:string;delivery_address:string|null;delivery_zone:string|null;created_at:string}
const statusLabel:Record<string,string>={pending:'En attente',confirmed:'Confirmée',preparing:'Préparation',ready:'Prête',shipped:'Expédiée',delivered:'Livrée',cancelled:'Annulée',rejected:'Refusée'}
const paymentLabel:Record<string,string>={pending:'Paiement en attente',authorized:'Paiement autorisé',paid:'Payée',failed:'Paiement échoué',refunded:'Remboursée',cash_on_delivery:'Paiement à la livraison'}

export function CommandesScreen(){
 const {soleilMode,goBack,merchantId}=useAppStore(); const online=useNetworkStatus()
 const [orders,setOrders]=useState<Order[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selected,setSelected]=useState<Order|null>(null); const [detail,setDetail]=useState<any>(null); const [paying,setPaying]=useState(false); const [receiving,setReceiving]=useState(false)
 const load=useCallback(async()=>{if(!merchantId)return;setLoading(true);setError(null);try{const res=await fetch('/api/marketplace/my-orders?merchantId='+encodeURIComponent(merchantId),{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data?.erreur||'Erreur');setOrders(data.orders||[])}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les commandes')}finally{setLoading(false)}},[merchantId])
 useEffect(()=>{void load()},[load])
 const open=async(o:Order)=>{setSelected(o);setDetail(null);try{const res=await fetch('/api/marketplace/orders/'+o.id);const d=await res.json();if(res.ok)setDetail(d)}catch{}}
 const cancel=async()=>{if(!selected)return;const res=await fetch('/api/marketplace/orders/'+selected.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel',reason:'Annulation par le marchand'})});if(res.ok){playBeep('success');haptic('success');tataSpeak('Commande annulée.');setSelected(null);void load()}}
 const confirmReceipt=async()=>{if(!selected||receiving)return;setReceiving(true);try{const res=await fetch('/api/marketplace/orders/'+selected.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'receipt'})});const d=await res.json();if(!res.ok)throw new Error(d?.erreur||'Confirmation impossible');playBeep('success');haptic('success');tataSpeak('Réception de la commande confirmée.');setSelected(null);void load()}catch(e){setError(e instanceof Error?e.message:'Confirmation impossible')}finally{setReceiving(false)}}
 const initiatePayment=async(method:string)=>{if(!selected||paying)return;setPaying(true);try{const res=await fetch('/api/marketplace/orders/'+selected.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'payment',paymentMethod:method})});const d=await res.json();if(!res.ok)throw new Error(d?.erreur||'Paiement impossible');playBeep('success');haptic('success');tataSpeak('Paiement enregistré en attente de confirmation.');setDetail((x:any)=>x?{...x,order:{...x.order,payment_method:method,payment_status:'pending'},payments:[d.payment,...(x.payments||[])]}:x);void load()}catch(e){setError(e instanceof Error?e.message:'Paiement impossible')}finally{setPaying(false)}}
 return <div className='screen-enter pb-[calc(6rem+env(safe-area-inset-bottom))]'><header className='sticky top-0 z-40 bg-background border-b px-4 py-3'><div className='flex items-center gap-2'><Button variant='ghost' size='icon' className='h-11 w-11' onClick={goBack}><ArrowLeft className='w-5 h-5'/></Button><div><h1 className={soleilMode?'text-xl font-bold text-black':'text-lg font-bold'}>Mes commandes marketplace</h1><p className='text-xs text-muted-foreground'>Suivi, paiement et réception</p></div><Button variant='ghost' size='icon' className='ml-auto' onClick={()=>void load()}><RefreshCw className='w-4 h-4'/></Button></div></header>
 <div className='px-4 mt-4 space-y-3'>{loading&&Array.from({length:4}).map((_,i)=><Card key={i}><CardContent className='p-4'><div className='h-5 w-2/3 bg-muted animate-pulse rounded'/><div className='h-4 w-1/3 bg-muted animate-pulse rounded mt-2'/></CardContent></Card>)}{!loading&&error&&<Card><CardContent className='p-5 text-center'><p className='text-sm text-red-600'>{error}</p><Button variant='outline' className='mt-3' onClick={load}>Réessayer</Button></CardContent></Card>}{!loading&&!error&&!orders.length&&<Card className='border-dashed'><CardContent className='p-10 text-center'><Package className='w-10 h-10 mx-auto mb-2 text-muted-foreground'/><p className='text-sm text-muted-foreground'>Aucune commande marketplace.</p></CardContent></Card>}{orders.map(o=><Card key={o.id} className='cursor-pointer' onClick={()=>void open(o)}><CardContent className='p-4'><div className='flex items-start gap-3'><div className='w-10 h-10 rounded-lg bg-[#FDF3ED] flex items-center justify-center'><Package className='w-5 h-5 text-[#C66A2C]'/></div><div className='min-w-0 flex-1'><p className='font-semibold text-sm'>{o.order_number}</p><p className='text-xs text-muted-foreground mt-1'>{new Date(o.created_at).toLocaleDateString('fr-FR')}</p></div><Badge>{statusLabel[o.status]||o.status}</Badge></div><div className='flex justify-between mt-3 pt-3 border-t'><span className='text-xs text-muted-foreground'>{paymentLabel[o.payment_status]||o.payment_status}</span><span className='font-bold text-[#C66A2C]'>{formatFCFA(Number(o.total_cfa))}</span></div></CardContent></Card>)}</div>
 <Dialog open={!!selected} onOpenChange={x=>!x&&setSelected(null)}><DialogContent className='max-w-lg'><DialogHeader><DialogTitle>{selected?.order_number}</DialogTitle><DialogDescription>Historique de votre commande</DialogDescription></DialogHeader>{selected&&<div className='space-y-4'><div className='grid grid-cols-2 gap-2'><Info label='Statut' value={statusLabel[selected.status]||selected.status}/><Info label='Paiement' value={paymentLabel[selected.payment_status]||selected.payment_status}/><Info label='Réception' value={selected.delivery_status}/><Info label='Total' value={formatFCFA(Number(selected.total_cfa))}/></div>{detail?.items?.length&&<div className='space-y-2'>{detail.items.map((i:any)=><div key={i.id} className='flex justify-between border rounded-lg p-2'><span className='text-sm'>{i.quantity} × {i.product_name}</span><span className='text-sm font-semibold'>{formatFCFA(Number(i.subtotal_cfa))}</span></div>)}</div>}{detail?.events?.length&&<div><p className='text-sm font-semibold mb-2'>Suivi</p><div className='space-y-2'>{detail.events.map((e:any)=><div key={e.id} className='flex gap-2 text-xs'><Clock className='w-3.5 h-3.5 text-[#C66A2C] mt-0.5'/><span>{e.event_type} · {new Date(e.created_at).toLocaleString('fr-FR')}</span></div>)}</div></div>}{selected.payment_status==='pending'&&<div><p className='text-sm font-semibold mb-2'>Choisir un paiement</p><div className='grid grid-cols-2 gap-2'><Button disabled={paying} onClick={()=>void initiatePayment('mobile_money')}><CreditCard className='w-4 h-4 mr-1'/>Mobile Money</Button><Button variant='outline' disabled={paying} onClick={()=>void initiatePayment('cash')}><CreditCard className='w-4 h-4 mr-1'/>Espèces</Button></div></div>}{selected.status==='pending'&&<Button variant='outline' className='w-full text-red-600' onClick={()=>void cancel()}><X className='w-4 h-4 mr-1'/>Annuler la commande</Button>}{selected.status==='delivered'&&!selected.buyer_received_at&&<Button className='w-full min-h-11 bg-emerald-600 hover:bg-emerald-700 text-white' disabled={receiving} onClick={()=>void confirmReceipt()}><CheckCircle2 className='w-4 h-4 mr-2'/>{receiving?'Confirmation…':'Confirmer que j’ai reçu la commande'}</Button>}{selected.status==='delivered'&&selected.buyer_received_at&&<div className='rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700 flex gap-2'><CheckCircle2 className='w-4 h-4 mt-0.5'/>Réception confirmée.</div>}{!online&&<p className='text-xs text-amber-700 flex gap-2'><WifiOffIcon/>Hors ligne : actualisation et paiement nécessitent la connexion.</p>}</div>}<DialogFooter><Button variant='outline' onClick={()=>setSelected(null)}>Fermer</Button></DialogFooter></DialogContent></Dialog></div>
}
function Info({label,value}:{label:string;value:string}){return <div className='rounded-lg border p-3'><p className='text-[11px] text-muted-foreground'>{label}</p><p className='text-sm font-semibold mt-1'>{value}</p></div>}
function WifiOffIcon(){return <span className='inline-flex'><WifiOff className='w-3.5 h-3.5'/></span>}
