'use client'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ShoppingCart, Plus, Minus, Trash2, Package, Search, WifiOff, ChevronRight } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { useAppStore } from '@/lib/stores/app-store'
import { formatFCFA } from '@/lib/utils'
import { tataSpeak, haptic, playBeep } from '@/lib/voice/tata-tts'
import { useNetworkStatus } from '@/lib/hooks/use-network-status'
type Listing={id:string;sellerId:string;productId:string;title:string;description:string|null;category:string;priceUnit:number;currency:string;minOrderQuantity:number;maxOrderQuantity:number|null;seller:{merchant_id:string;display_name:string|null;description:string|null;zone:string|null;phone:string|null;status:string};images:{image_url:string;position:number;alt_text:string|null}[]}
type CartItem={listing:Listing;quantity:number}
const CART_KEY='julaba-marketplace-cart-v1'
const paymentLabels:Record<string,string>={cash:'Espèces',mobile_money:'Mobile Money',card:'Carte',wallet:'Portefeuille',cash_on_delivery:'Paiement à la livraison',other:'Autre'}
export function MarcheScreen(){
 const {soleilMode,goBack,merchantId,navigate}=useAppStore(); const online=useNetworkStatus()
 const [listings,setListings]=useState<Listing[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState(''); const [category,setCategory]=useState(''); const [cart,setCart]=useState<CartItem[]>([]); const [cartOpen,setCartOpen]=useState(false); const [checkoutOpen,setCheckoutOpen]=useState(false); const [paymentMethod,setPaymentMethod]=useState('cash_on_delivery'); const [deliveryMode,setDeliveryMode]=useState<'pickup'|'delivery'|'courier'>('pickup'); const [address,setAddress]=useState(''); const [zone,setZone]=useState(''); const [note,setNote]=useState(''); const [submitting,setSubmitting]=useState(false); const [orderError,setOrderError]=useState<string|null>(null)
 useEffect(()=>{try{const raw=localStorage.getItem(CART_KEY);if(raw)setCart(JSON.parse(raw))}catch{}},[]); useEffect(()=>{try{localStorage.setItem(CART_KEY,JSON.stringify(cart))}catch{}},[cart])
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const p=new URLSearchParams({limit:'100'});if(category)p.set('category',category);if(search.trim())p.set('q',search.trim());const res=await fetch('/api/marketplace?'+p,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data?.erreur||'Catalogue indisponible');setListings(data.listings||[])}catch(e){setError(e instanceof Error?e.message:'Catalogue indisponible')}finally{setLoading(false)}},[category,search])
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t)},[load])
 const categories=useMemo(()=>[...new Set(listings.map(x=>x.category))].sort((a,b)=>a.localeCompare(b,'fr')),[listings]); const total=cart.reduce((s,x)=>s+x.quantity*x.listing.priceUnit,0)
 const updateQty=(id:string,d:number)=>setCart(xs=>xs.map(x=>x.listing.id===id?{...x,quantity:Math.max(x.listing.minOrderQuantity,x.quantity+d)}:x).filter(x=>x.quantity>0)); const remove=(id:string)=>setCart(xs=>xs.filter(x=>x.listing.id!==id))
 const add=(l:Listing)=>{setCart(xs=>{const f=xs.find(x=>x.listing.id===l.id);if(f)return xs.map(x=>x.listing.id===l.id?{...x,quantity:Math.min(l.maxOrderQuantity??999999,x.quantity+l.minOrderQuantity)}:x);return [...xs,{listing:l,quantity:l.minOrderQuantity}]});playBeep('success');haptic('light')}
 const checkout=async()=>{if(!merchantId||!cart.length||!online)return;setSubmitting(true);setOrderError(null);try{const res=await fetch('/api/marketplace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buyerMerchantId:merchantId,clientId:crypto.randomUUID(),items:cart.map(x=>({listingId:x.listing.id,quantity:x.quantity})),paymentMethod,deliveryMode,deliveryAddress:address.trim()||null,deliveryZone:zone.trim()||null,buyerNote:note.trim()||null})});const data=await res.json();if(!res.ok)throw new Error(data?.erreur==='INSUFFICIENT_MARKETPLACE_STOCK'?'Stock insuffisant. Disponible : '+(data.available??0):(data?.erreur||'Commande refusée'));setCart([]);setCheckoutOpen(false);setCartOpen(false);playBeep('success');haptic('success');tataSpeak('Commande enregistrée. Total '+formatFCFA(Number(data.order?.total_cfa||total))+'.');navigate('commandes')}catch(e){setOrderError(e instanceof Error?e.message:'Impossible de passer la commande')}finally{setSubmitting(false)}}
 return <div className='screen-enter pb-[calc(6rem+env(safe-area-inset-bottom))]'>
 <header className='sticky top-0 z-40 bg-background border-b px-4 py-3'><div className='flex items-center justify-between gap-2'><div className='flex items-center gap-2'><Button variant='ghost' size='icon' className='h-11 w-11' onClick={goBack}><ArrowLeft className='w-5 h-5'/></Button><div><h1 className={soleilMode?'text-xl font-bold text-black':'text-lg font-bold'}>Marché Jùlaba</h1><p className='text-xs text-muted-foreground'>Acheter directement auprès des marchands</p></div></div><Button variant='outline' size='icon' className='relative h-11 w-11' onClick={()=>setCartOpen(true)}><ShoppingCart className='w-5 h-5'/>{cart.length>0&&<Badge className='absolute -right-1 -top-1 h-5 min-w-5 px-1 text-[10px]'>{cart.length}</Badge>}</Button></div>{!online&&<div className='mt-2 text-xs text-amber-700 flex items-center gap-1.5'><WifiOff className='w-3.5 h-3.5'/>Catalogue consultable, commande indisponible hors connexion.</div>}</header>
 <div className='px-4 pt-4 space-y-3'><div className='relative'><Search className='absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground'/><Input className='pl-9 min-h-11' value={search} onChange={e=>setSearch(e.target.value)} placeholder='Rechercher un produit…'/></div>{categories.length>0&&<div className='flex gap-2 overflow-x-auto pb-1'>{['',...categories].map(c=><Button key={c||'tous'} size='sm' variant={category===c?'default':'outline'} className='shrink-0' onClick={()=>setCategory(c)}>{c||'Tous'}</Button>)}</div>}</div>
 <div className='px-4 mt-4 space-y-3'>{loading&&Array.from({length:5}).map((_,i)=><Card key={i}><CardContent className='p-4'><div className='h-28 bg-muted rounded-xl animate-pulse'/></CardContent></Card>)}{!loading&&error&&<Card><CardContent className='p-6 text-center'><p className='text-sm text-red-600'>{error}</p><Button variant='outline' className='mt-3' onClick={load}>Réessayer</Button></CardContent></Card>}{!loading&&!error&&!listings.length&&<Card className='border-dashed'><CardContent className='p-10 text-center'><Package className='w-10 h-10 mx-auto mb-2 text-muted-foreground'/><p className='text-sm text-muted-foreground'>Aucun produit publié.</p></CardContent></Card>}{!loading&&!error&&listings.map(l=><Card key={l.id}><CardContent className='p-3 flex gap-3'><div className='w-24 h-24 rounded-xl overflow-hidden bg-muted shrink-0'>{l.images[0]?<img src={l.images[0].image_url} alt={l.images[0].alt_text||l.title} className='w-full h-full object-cover'/>:<div className='h-full flex items-center justify-center'><Package className='w-8 h-8 text-muted-foreground'/></div>}</div><div className='min-w-0 flex-1'><div className='flex justify-between gap-2'><div><h2 className='font-semibold text-sm truncate'>{l.title}</h2><p className='text-xs text-muted-foreground'>{l.seller.display_name||'Marchand'}{l.seller.zone?' · '+l.seller.zone:''}</p></div><span className='font-bold text-sm text-[#C66A2C] whitespace-nowrap'>{formatFCFA(l.priceUnit)}</span></div>{l.description&&<p className='text-xs text-muted-foreground mt-1 line-clamp-2'>{l.description}</p>}<div className='flex items-center justify-between mt-3'><span className='text-[11px] text-muted-foreground'>Minimum {l.minOrderQuantity}</span><Button size='sm' className='min-h-10 bg-[#C66A2C] text-white' onClick={()=>add(l)}><Plus className='w-4 h-4 mr-1'/>Ajouter</Button></div></div></CardContent></Card>)}</div>
 <Dialog open={cartOpen} onOpenChange={setCartOpen}><DialogContent className='max-w-lg'><DialogHeader><DialogTitle>Mon panier</DialogTitle><DialogDescription>Vérifiez les quantités.</DialogDescription></DialogHeader><div className='space-y-3 max-h-[50vh] overflow-auto'>{!cart.length?<p className='text-sm text-muted-foreground text-center py-8'>Panier vide.</p>:cart.map(x=><div key={x.listing.id} className='flex gap-3 items-center'><div className='min-w-0 flex-1'><p className='font-medium text-sm truncate'>{x.listing.title}</p><p className='text-xs text-muted-foreground'>{formatFCFA(x.listing.priceUnit)} / unité</p></div><div className='flex items-center gap-1'><Button size='icon' variant='outline' className='h-9 w-9' onClick={()=>updateQty(x.listing.id,-x.listing.minOrderQuantity)}><Minus className='w-4 h-4'/></Button><span className='w-10 text-center'>{x.quantity}</span><Button size='icon' variant='outline' className='h-9 w-9' disabled={x.listing.maxOrderQuantity!=null&&x.quantity>=x.listing.maxOrderQuantity} onClick={()=>updateQty(x.listing.id,x.listing.minOrderQuantity)}><Plus className='w-4 h-4'/></Button><Button size='icon' variant='ghost' className='h-9 w-9 text-red-600' onClick={()=>remove(x.listing.id)}><Trash2 className='w-4 h-4'/></Button></div></div>)}</div><div className='flex justify-between font-bold border-t pt-3'><span>Total produits</span><span className='text-[#C66A2C]'>{formatFCFA(total)}</span></div><DialogFooter><Button variant='outline' onClick={()=>setCartOpen(false)}>Continuer</Button><Button disabled={!cart.length} onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>Passer la commande<ChevronRight className='w-4 h-4 ml-1'/></Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={checkoutOpen} onOpenChange={setCheckoutOpen}><DialogContent className='max-w-lg'><DialogHeader><DialogTitle>Finaliser la commande</DialogTitle><DialogDescription>Le stock sera vérifié au moment de la confirmation.</DialogDescription></DialogHeader><div className='space-y-4'><div><p className='text-sm font-semibold mb-2'>Paiement</p><div className='grid grid-cols-2 gap-2'>{Object.entries(paymentLabels).map(([k,v])=><Button key={k} type='button' variant={paymentMethod===k?'default':'outline'} className='min-h-11' onClick={()=>setPaymentMethod(k)}>{v}</Button>)}</div></div><div><p className='text-sm font-semibold mb-2'>Réception</p><div className='grid grid-cols-3 gap-2'><Button variant={deliveryMode==='pickup'?'default':'outline'} onClick={()=>setDeliveryMode('pickup')}>Enlèvement</Button><Button variant={deliveryMode==='delivery'?'default':'outline'} onClick={()=>setDeliveryMode('delivery')}>Livraison</Button><Button variant={deliveryMode==='courier'?'default':'outline'} onClick={()=>setDeliveryMode('courier')}>Coursier</Button></div></div>{deliveryMode!=='pickup'&&<><Input value={address} onChange={e=>setAddress(e.target.value)} placeholder='Adresse de livraison'/><Input value={zone} onChange={e=>setZone(e.target.value)} placeholder='Commune / zone'/></>}{orderError&&<p className='text-sm text-red-600'>{orderError}</p>}</div><DialogFooter><Button variant='outline' onClick={()=>setCheckoutOpen(false)}>Retour</Button><Button disabled={!online||submitting||!cart.length} onClick={checkout}>{submitting?'Vérification du stock…':'Confirmer '+formatFCFA(total)}</Button></DialogFooter></DialogContent></Dialog>
</div>}
