-- Migration : activation de la sécurité au niveau des lignes (RLS) sur legacy_supplier_orders
-- Objet concerné : table public.legacy_supplier_orders — aucune colonne ni donnée modifiée.
-- Sensibilité : élevée — ventes, dépenses, commandes fournisseurs et catalogue de l’exploitation
--
-- But : empêcher la lecture ou la falsification des données commerciales (chiffre d’affaires, marges, commandes) par un tiers disposant de la clé anon.
--
-- Pourquoi maintenant : cette table provient de la baseline « legacy » de
-- janvier 2026 (ou de la série initiale merchants/producers), créée avant
-- l’adoption de la discipline RLS de la série de septembre 2026. Tant que le
-- RLS reste désactivé, l’API REST PostgREST laisse les rôles anon et
-- authenticated lire et écrire librement ces lignes dès lors qu’ils possèdent
-- la clé anon — or celle-ci est embarquée dans le bundle applicatif et n’est
-- donc pas confidentielle. Activer le RLS ferme ce canal.
--
-- Stratégie de sécurité : verrouillage complet des rôles publics. Aucune
-- policy n’est volontairement créée pour anon ou authenticated : en Postgres,
-- l’absence de policy applicable équivaut à un refus (default deny). C’est le
-- modèle officiel recommandé par Supabase pour une table réservée au
-- service_role — écrire des policies « always false » n’apporterait rien et
-- brouillerait l’intention. La séparation des rôles reste granulaire par
-- construction : chaque opération (select/insert/update/delete) est refusée
-- indépendamment pour anon et authenticated.
--
-- Accès légitimes préservés : /api/marchand/* (ventes, dépenses, commandes fournisseurs) et /api/backoffice/marketplace via le client service_role.
-- Cas particulier : les commandes fournisseurs vocales ou tapées passent par /api/marchand/supplier-orders (service_role) avec rejeu idempotent hors-ligne côté client : aucun accès direct nécessaire.

-- Compatibilité : aucune route cliente ne requête cette table avec la clé
-- anon ; les tests pgTAP (supabase/tests/rls.sql) vérifient désormais que le
-- RLS est bien actif ici.
--
-- Idempotence : « alter table … enable row level security » est idempotent —
-- ré-exécuter cette migration sur une table déjà protégée est sans effet.

alter table public.legacy_supplier_orders enable row level security;
